#pragma once

#define TRUE 1
#define FALSE 0

#define F_OK TRUE
#define F_NOK FALSE

#define PERMISSION_EXECUTE
#define PERMISSION_READ
#define PERMISSION_WRITE

#define MESSAGE_START_CONTAINER_RUNTIME
#define MESSAGE_START_CHILD_PROCESS
#define MESSAGE_CONTAINER_RUNTIME_ERROR
#define MESSAGE_START_CHILD_PROCESS_ERROR
#define MESSAGE_USER_ACCESS_ERROR
#define MESSAGE_STACK_ALLOCATION_ERROR